package ui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class MainGUI extends JFrame {

    private final JFrame frame;
    private JButton showBooksBtn;
    private JButton searchBtn;
    private JButton insertBtn;
    private JButton quitBtn;
    private JTextField searchField;
    private JPanel mainPanel;
    private JPanel resultsPanel;
    private JScrollPane booksScrollPane;

    private ArrayList<JButton> deleteButtons = new ArrayList<>();

    public MainGUI() {

        frame = new JFrame("Book Logger");
        frame.setContentPane(mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);

        resultsPanel.setLayout(new BoxLayout(resultsPanel, BoxLayout.PAGE_AXIS));
        resultsPanel.setAlignmentX(LEFT_ALIGNMENT);

        booksScrollPane.setAutoscrolls(true);
        booksScrollPane.setAlignmentX(LEFT_ALIGNMENT);

        searchField.setToolTipText("type book's or author's name to search");

    }

    //it would be better to iterate the list in the Controller and pass each entry here ?
    public void showBooksGui(List<LinkedHashMap<String, String>> books, Boolean deleteButton) {

        resultsPanel.removeAll();
        deleteButtons.clear();

        for (Map<String, String> bookMap : books) {

            Box labelBox = Box.createVerticalBox();
            labelBox.setAlignmentX(LEFT_ALIGNMENT);

            JPanel bookPanel = new JPanel();
            bookPanel.setAlignmentX(LEFT_ALIGNMENT);
            bookPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));

            resultsPanel.add(bookPanel);
            bookPanel.add(labelBox);

            if (deleteButton) {
                JButton deleteBtn = new JButton("delete");
                deleteBtn.setActionCommand(String.valueOf(deleteButtons.size()));
                deleteButtons.add(deleteBtn);
                bookPanel.add(deleteBtn);
            }

            for (Map.Entry<String, String> entry : bookMap.entrySet()) {
                JLabel info = new JLabel(entry.getValue());
                info.setAlignmentX(LEFT_ALIGNMENT);
                labelBox.add(info);
            }

            resultsPanel.add(Box.createHorizontalStrut(2));

            resultsPanel.revalidate();
            resultsPanel.repaint();

        }

        resultsPanel.revalidate();
        resultsPanel.repaint();

    }

    public void showPopUpMain(String error) {

        JOptionPane.showMessageDialog(
                new JFrame(),
                error,
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }

    public void addQuitListener(ActionListener quitListener) {
        quitBtn.addActionListener(quitListener);

    }

    public void addShowBooksListener(ActionListener showBooksListener) {
        showBooksBtn.addActionListener(showBooksListener);

    }

    public void addInsertListener(ActionListener insertListener) {
        insertBtn.addActionListener(insertListener);
    }

    public void addSearchListener(ActionListener searchListener) {
        searchBtn.addActionListener(searchListener);
    }

    public ArrayList<JButton> getDeleteButtons() {
        return deleteButtons;
    }

    public String getFieldText() {
        return searchField.getText().toUpperCase();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 4, new Insets(0, 0, 0, 0), -1, -1));
        showBooksBtn = new JButton();
        showBooksBtn.setText("Show All Books");
        mainPanel.add(showBooksBtn, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        searchBtn = new JButton();
        searchBtn.setText("Search");
        mainPanel.add(searchBtn, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        insertBtn = new JButton();
        insertBtn.setText("Insert");
        mainPanel.add(insertBtn, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        quitBtn = new JButton();
        quitBtn.setText("Quit");
        mainPanel.add(quitBtn, new com.intellij.uiDesigner.core.GridConstraints(0, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        booksScrollPane = new JScrollPane();
        mainPanel.add(booksScrollPane, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 4, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(-1, 115), null, null, 0, false));
        resultsPanel = new JPanel();
        resultsPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        booksScrollPane.setViewportView(resultsPanel);
        searchField = new JTextField();
        searchField.setText("");
        searchField.setToolTipText("");
        mainPanel.add(searchField, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 4, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }


}
